/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mytabpanel',

    height: 131,
    width: 364,
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    width: 913,
                    title: 'Patients'
                },
                {
                    xtype: 'panel',
                    title: 'Destinations'
                },
                {
                    xtype: 'panel',
                    title: 'Drivers'
                },
                {
                    xtype: 'panel',
                    title: 'Transportation'
                },
                {
                    xtype: 'panel',
                    title: 'Special Requirements'
                },
                {
                    xtype: 'panel',
                    title: 'Special Requirements'
                }
            ]
        });

        me.callParent(arguments);
    }

});